#############################################################################
# Makefile for building: qchaos
# Generated by qmake (2.01a) (Qt 4.8.6) on: Sun Jul 13 20:35:03 2014
# Project:  qchaos.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile qchaos.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Imodels -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lqwt-qt4 -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = qchaos.cc \
		QChaosModel.cc \
		QChaosPlot.cc \
		QChaosWindow.cc \
		QParBox.cc \
		QParBoxArray.cc moc_QChaosModel.cpp \
		moc_QChaosPlot.cpp \
		moc_QChaosWindow.cpp \
		moc_QParBox.cpp \
		moc_QParBoxArray.cpp
OBJECTS       = qchaos.o \
		QChaosModel.o \
		QChaosPlot.o \
		QChaosWindow.o \
		QParBox.o \
		QParBoxArray.o \
		moc_QChaosModel.o \
		moc_QChaosPlot.o \
		moc_QChaosWindow.o \
		moc_QParBox.o \
		moc_QParBoxArray.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		qchaos.pro
QMAKE_TARGET  = qchaos
DESTDIR       = 
TARGET        = qchaos

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qchaos.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile qchaos.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile qchaos.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qchaos1.0.0 || $(MKDIR) .tmp/qchaos1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qchaos1.0.0/ && $(COPY_FILE) --parents QChaosModel.hh QChaosPlot.hh QChaosWindow.hh QParBox.hh QParBoxArray.hh models/QChaosAronson.hh models/QChaosBarnsley.hh models/QChaosHenon.hh models/QChaosHenonC.hh models/QChaosLorentz.hh models/QChaosLozi.hh models/QChaosSmith.hh .tmp/qchaos1.0.0/ && $(COPY_FILE) --parents qchaos.cc QChaosModel.cc QChaosPlot.cc QChaosWindow.cc QParBox.cc QParBoxArray.cc .tmp/qchaos1.0.0/ && (cd `dirname .tmp/qchaos1.0.0` && $(TAR) qchaos1.0.0.tar qchaos1.0.0 && $(COMPRESS) qchaos1.0.0.tar) && $(MOVE) `dirname .tmp/qchaos1.0.0`/qchaos1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qchaos1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_QChaosModel.cpp moc_QChaosPlot.cpp moc_QChaosWindow.cpp moc_QParBox.cpp moc_QParBoxArray.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_QChaosModel.cpp moc_QChaosPlot.cpp moc_QChaosWindow.cpp moc_QParBox.cpp moc_QParBoxArray.cpp
moc_QChaosModel.cpp: QChaosModel.hh
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) QChaosModel.hh -o moc_QChaosModel.cpp

moc_QChaosPlot.cpp: QChaosPlot.hh
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) QChaosPlot.hh -o moc_QChaosPlot.cpp

moc_QChaosWindow.cpp: QChaosWindow.hh
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) QChaosWindow.hh -o moc_QChaosWindow.cpp

moc_QParBox.cpp: QParBox.hh
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) QParBox.hh -o moc_QParBox.cpp

moc_QParBoxArray.cpp: QParBoxArray.hh
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) QParBoxArray.hh -o moc_QParBoxArray.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

qchaos.o: qchaos.cc QChaosWindow.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qchaos.o qchaos.cc

QChaosModel.o: QChaosModel.cc QChaosModel.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QChaosModel.o QChaosModel.cc

QChaosPlot.o: QChaosPlot.cc QChaosPlot.hh \
		QChaosModel.hh \
		models/QChaosHenon.hh \
		models/QChaosLozi.hh \
		models/QChaosAronson.hh \
		models/QChaosHenonC.hh \
		models/QChaosBarnsley.hh \
		models/QChaosSmith.hh \
		models/QChaosLorentz.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QChaosPlot.o QChaosPlot.cc

QChaosWindow.o: QChaosWindow.cc QChaosWindow.hh \
		QChaosPlot.hh \
		QChaosModel.hh \
		QParBoxArray.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QChaosWindow.o QChaosWindow.cc

QParBox.o: QParBox.cc QParBox.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QParBox.o QParBox.cc

QParBoxArray.o: QParBoxArray.cc QParBox.hh \
		QParBoxArray.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QParBoxArray.o QParBoxArray.cc

moc_QChaosModel.o: moc_QChaosModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QChaosModel.o moc_QChaosModel.cpp

moc_QChaosPlot.o: moc_QChaosPlot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QChaosPlot.o moc_QChaosPlot.cpp

moc_QChaosWindow.o: moc_QChaosWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QChaosWindow.o moc_QChaosWindow.cpp

moc_QParBox.o: moc_QParBox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QParBox.o moc_QParBox.cpp

moc_QParBoxArray.o: moc_QParBoxArray.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QParBoxArray.o moc_QParBoxArray.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

